### ISSUE TITLE
Subscribe Instructions link 404s

### ISSUE THREAD

**Issue by brookienoodle** [privacy/subprocessors#4] opened 2022-10-28 18:39 UTC
Hey hey! @J3nnie how goes it? I'm checking out how you're managing your subprocessor list notifications, and I noticed that the instructions link in the README 404s https://github.com/privacy/resources/blob/main/subscribe.md. I also see this same link in the Cookies repo, so same issue there. 

I assume to get notified of a subprocessor change, you need to watch `All Activity` or `Custom` (which I think is new since I left last year).  

Edit: I noticed you just made this change, and [the original instructions were in the last version](https://github.com/privacy/subprocessors/commit/aac84622ea483d89fe854da24e4419f2eb16636d).

**Comment by J3nnie** [comment] 2022-11-18 23:46
👋 Hey @brookienoodle good hearing from you!

Glad the problem is now resolved for you 🎉 , so closing this issue 😉

**Closed by J3nnie** 2022-11-18 23:46 UTC
